---
title: "CE085 - Estatística Inferencial"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

<!-- <div class="alert alert-danger" role="alert"> **ATENÇÃO!** Aqui é um -->
<!-- espaço para avisos. Comente quando não utilizar. </div> -->

# Detalhes da oferta da disciplina

- **Curso:** Bacharelado em Estatística (N).
- **Período:** Segundo semestre de 2018.
- **Professor Responsável:** [Wagner Hugo Bonat](http://www.leg.ufpr.br/~wagner), ([LEG][]:
  Laboratório de Estatística e Geoinformação, sala 227, prédio de Exatas)
- **Horários e Locais:**
    - Segunda, 19:00 - 20:30h, **PA09**
    - Quarta, 20:45 - 22:15h, **PC04**
    - Quinta, 19:00 - 20:30h, **PC04**
- **Horários de atendimento do professor:**
    - Quintas e sextas, 14:00-18:00 (preferenciais). Outros horários
      podem ser agendados previamente por email.
- **Frequência**: de acordo com as normas da Universidade, mínimo de 75%
- **Avaliação**: serão realizadas 2 avaliações e um trabalho durante o semestre
    - As datas das provas serão definidas conforme o andamento da
      disciplina.
    - A média final será a média simples das 2 avaliações e do trabalho (todas tem o mesmo
      peso).
- **Datas importantes:** De acordo com a resolução 31/17-CEPE:
    - **30/07**: Início do semestre letivo
    - **03/12**: Final do semestre letivo
    - **10/12-15/12**: Período de exames

# Programa/objetivos da disciplina

O objetivo deste curso é apresentar os conceitos básicos da inferência
estatística. O curso introduz as principais idéias do pensamento
estatístico do ponto de vista frequentista. Ênfase é dada a métodos de 
estimação e suas propriedades assintóticas. Pretende-se manter o curso
em um nível intermediário de rigorosidade matemática. A demonstração
formal dos principais teoremas será feita com riqueza de detalhes e
sempre que possível acompanhada de estudos de simulação para exemplificar
a aplicação prática dos teoremas. O curso é dividido em quatro etapas:

- Introdução ao pensamento estatístico.
- Revisão e exemplificação computacional de ferramentas da teoria de probabilidade.
- Inferência estatística.
- Métodos computacionais para Inferência estatística.

O curso será baseado em três materiais (arquivos formato pdf) que estão 
disponibilizados na aba "Materiais". Além disso, no decorrer do curso
um conjunto de notas de aulas no formato de slides será disponibilizado.

<!-- links -->

[LEG]: http://www.leg.ufpr.br